server:
  port: 8081
spring:
  application:
    name: courses-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

students-service:
  url: ${STUDENTS_URL}

